made changes

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,21 +1,24 @@
 #!/usr/bin/env bash
-# Check if all 4 parameters are provided
-if [ $# -ne 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+#Write a Bash script that transfers a file from our client to a server:
+
+# check if there are enough parameters
+if [ $# -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-PATH_TO_FILE="$1"
-IP="$2"
-USERNAME="$3"
-PATH_TO_SSH_KEY="$4"
+# set variables for the parameters
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
 
-# Transfer the file using scp
-scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
+# transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/
 
-# Check the return code of scp and display success/failure message
+# check the exit code of scp
 if [ $? -eq 0 ]; then
-    echo "File transfer successful!"
+  echo "File transfer successful"
 else
-    echo "File transfer failed!"
+  echo "File transfer failed"
 fi
