chaange

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,10 +1,21 @@
 #!/usr/bin/env bash
-# This is a bash script that transfers a file from a client to a server using scp
+# Check if all 4 parameters are provided
+if [ $# -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
 
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+PATH_TO_FILE="$1"
+IP="$2"
+USERNAME="$3"
+PATH_TO_SSH_KEY="$4"
+
+# Transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
+
+# Check the return code of scp and display success/failure message
+if [ $? -eq 0 ]; then
+    echo "File transfer successful!"
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+    echo "File transfer failed!"
 fi
